### ISSUE TITLE
 <oid_num_indexes> missing in XML file, Index Count: 0, No SNMP data returned

### ISSUE THREAD

**Issue by ghost** [scline/CactiTemplate_JuniperNetworks#1]
It seems that the templates do not specify an index OID.

I added your templates in Cacti and tested with a Juniper SRX 260 (supported?)

It did not seem to return results, and running a Verbose Query usually stated "<oid_num_indexes> missing in XML file"

Here is an example Verbose Query in Cacti for "Juniper SRX - Central Point Statistics"

```
    + Running data query [10].
    + Found type = '3' [SNMP Query].
    + Found data query XML file at '/var/www/cacti/resource/snmp_queries/juniper_srx_central_point.xml'
    + XML file parsed ok.
    + <oid_num_indexes> missing in XML file, 'Index Count Changed' emulated by counting oid_index entries
    + Executing SNMP walk for list of indexes @ '' Index Count: 0
    + No SNMP data returned
```

**Comment by scline** [comment]
I'll take a look at this tomorrow, it should work on all SRX devices. 

What version of Junos are you running by chance?

**Comment by ghost** [comment]
not sure, I will have to check. I will get back to you.

**Comment by scline** [comment]
Can you run the following commands on your SRX device via cli, will show me
what values should be returning from the index listed in the xml file:

show snmp mib walk decimal 1.3.6.1.4.1.2636.3.39.1.12.1.4.1
show version

On my test device it looks like:
_scline@sc-srx220h-fw1> show snmp mib walk decimal
1.3.6.1.4.1.2636.3.39.1.12.1.4.1      *
*jnxJsClusterMonitoringNodeIndex.0 = 0_
_jnxJsClusterMonitoringNodeDescr.0 = single_
_jnxJsNodeCurrentTotalSession.0 = 329_
_jnxJsNodeMaxTotalSession.0 = 0_
_jnxJsNodeSessionCreationPerSecond.0 = 9_
_jnxJsNodeSessCreationPerSecIPv4.0 = 9_
_jnxJsNodeSessCreationPerSecIPv6.0 = 0_
_jnxJsNodeCurrentTotalSessIPv4.0 = 329_
_jnxJsNodeCurrentTotalSessIPv6.0 = 0_

_scline@sc-srx220h-fw1> show version                         *
*Hostname: sc-srx220h-fw1_
_Model: srx220h_
_JUNOS Software Release [12.1X44-D40.2]_

I just reimported the version online and cacti was able to pickup the
index. What version of cacti are you using?

**Comment by ghost** [comment]
Sadly I do not have direct access to the SRX260 to run the commands but I
can tell you

JunOS version : 10.4R6.5
Cacti version: cacti-0.8.8b-1

Does that help?

What version of cacti are you using?
I may be able to change the version.
The firewall will be upgraded soon to JunOS 12.1X44

**Comment by ghost** [comment]
after checking from an external device, the last OID that i can view
is 1.3.6.1.4.1.2636.3.39.1.12.1
It seems to be a difference in the JunOS version implementation of SNMP
OIDs, or is there some other configuration that may need to be changed?

**Comment by scline** [comment]
Closing issue due to OS version not having the correct SNMP OID.
