### ISSUE TITLE
No graph data available in cacti

### ISSUE THREAD

**Issue by dhavalsoni88** [scline/CactiTemplate_JuniperNetworks#3]
I've used this template to check traffic between each security policies in my Juniper SRX 210 Firewall. But, its not generating any graph data. Instead I am getting Index column in Cacti as Below:

11.70.117.108.108.45.77.97.110.97.103.101.11.70.117.108.108.45.77.97.110.97.103.101.7.68.101.102.97.117.108.116

11.70.117.108.108.45.77.97.110.97.103.101.5.116.114.117.115.116.15.66.70.87.71.45.70.117.108.108.77.97.110.97.103.101

My Cacti Version is: 0.8.8.f
NetSNMP: 5.7
RRDTool: 1.4.8
Juniper SRX OS: JunOS 12.1X46-D35.1

**Comment by dhavalsoni88** [comment]
![data query output](https://cloud.githubusercontent.com/assets/16209363/12789414/c3efebea-cac3-11e5-8a62-8118f297133a.JPG)
![srx no graph output](https://cloud.githubusercontent.com/assets/16209363/12789482/098e214e-cac4-11e5-8fbe-6ce87f176469.jpg)

**Comment by scline** [comment]
Do you have "then count" enabled on those policies? Without the count
settings unfortunately this data isnt available via SNMP/Cacti.

**Comment by dhavalsoni88** [comment]
Thanks Scline It woked. It was not enabled in any security policies, however I've enabled for few policies. its now graphing with data. 
But, I am getting SNMP OID in Index Column which is same as previous snap of DataQuery.

**Comment by dhavalsoni88** [comment]
I am getting SNMP OID in Index Column which is same as previous snap of DataQuery.

**Comment by dhavalsoni88** [comment]
Hi Scline,

Hope you are doing good.

few days back I've upgraded cacti, php, apache and Base OS. Upgrade details is as follows:
PHP: 7.0.7
Apache: 2.4
Base OS: CentOS 7.2.1511
Cacti: 1.0.0

everything was working fine before upgrade, but now I am facing strange issue. After selecting “Juniper SRX - Security Policy - Traffic” template and creating graphs, the output of template looks like “Juniper SRX Policy issue 01” image. 

Even neglecting above and move further to create graphs, I’ve selected few graphs which shows value in index (but rest of columns have null value) and few graphs have null value in index column but have values in rest of the columns (details contains in From zone, To Zone, Policy name etc.) But the graph name contain “xxx-Security Policy Traffic” able to generate graph but no value in graphs while another graph name contain “XXX-Policy-traffic- |query_PolicyName|” not able to even generate rrd files. You can view the attached “Juniper SRX Policy issue 02” and “Juniper SRX Policy issue 03” images for reference.

Can you help me here please.?

![juniper srx policy issue 01](https://cloud.githubusercontent.com/assets/16209363/15956447/4091cfbe-2f06-11e6-93d5-6c9f4294f8f1.jpg)
![juniper srx policy issue 02](https://cloud.githubusercontent.com/assets/16209363/15956460/5025caa2-2f06-11e6-90de-b33489c99c7e.jpg)
![juniper srx policy issue 03](https://cloud.githubusercontent.com/assets/16209363/15956461/502a924e-2f06-11e6-969a-d3f6e100e95c.jpg)

**Comment by dhavalsoni88** [comment]
Any update on this please?

**Comment by scline** [comment]
Sorry doing some cleanup on this repo, Cacti 1.0 was in beta at the time of your writing this (there were lots of bugs). By chance is this still a persisting issue or has the more prod-ready Cacti 1.1.X cleaned this up?
